name: clm_dev_ci-cd
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
 
env: 
  JAVA_HOME: "/apps-shared/tools/jdk17"
  MAVEN_HOME: "/apps-shared/tools/maven/bin"
  TOOL_HOME: "/apps-shared/tools/"
  SCANNER_HOME: "/apps-shared/tools/sonar-scanner-5.0.1.3006-linux"

jobs:
  cicd_amp_clm_ms_dev:
    runs-on: ['e3-devsecops-runners']
 
    steps:
      - name: Load Secrets
        uses: hashicorp/vault-action@v3.0.0
        id: vault
        with:
         url: https://vault.appsec.corp.equinix.com
         namespace: e3-devsecops
         method: kubernetes
         path: github-vault
         role: github-runners-role
         secrets: |
            prod/data/cicd github_app_id | GITHUB_APP_ID;
            prod/data/cicd github_app_key | GITHUB_PRIVATE_KEY;
            prod/data/cicd nexus-username | DOCKER_NEXUS_USERNAME;
            prod/data/cicd nexus-password | DOCKER_NEXUS_PASSWORD;
            prod/data/cicd prismacloud-password | PRISMACLOUD_PASSWORD;
            prod/data/cicd prismacloud-username | PRISMACLOUD_USER;
            prod/data/kubeconfig/amp ${{ inputs.environment }} | KUBECONFIG
 
      - name: checkout
        uses: actions/checkout@v4 
        with: 
          ref: 'develop'
          fetch-depth: 1
 
      - name: Build and analyze
        run: | 
            $MAVEN_HOME/mvn clean package -Dmaven.test.skip=true -s  /apps-shared/tools/.m2/settings.xml -gs /apps-shared/tools/.m2/settings.xml;
 
      # - name: SonarQube Dynamic Token
      #   id: sonar-token
      #   uses: equinix-private/devsecops-sonarqube-action/.github/actions/sonarqube-token-generator@main
      #   with:
      #     INSTANCE: prod
      #     PROJECT_KEY: dart-ee-${{ inputs.module }}
      #     SONARQUBE_USERNAME: ${{ secrets.SONARQUBE_USERNAME }}
      #     SONARQUBE_PASSWORD: ${{ secrets.SONARQUBE_PASSWORD }}
 
      # - name: SonarQube Code Scan
      #   uses: sonarsource/sonarqube-scan-action@v2.0.2
      #   env:
      #     SONAR_TOKEN: ${{ steps.sonar-token.outputs.sonar-token }}
      #     SONAR_HOST_URL: ${{ vars.SONAR_ENTERPRISE_URL }}
      #   with:
      #     args: >
      #       -Dsonar.branch.name=${{ inputs.branch }}
 
      # - name: SonarQube Quality Gate
      #   if: inputs.module == 'dartmobile'
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   with:
      #      pollingTimeoutSec: 600
      #   env:
      #     SONAR_TOKEN: ${{ steps.sonar-token.outputs.sonar-token }}
      #     SONAR_HOST_URL: ${{ vars.SONAR_ENTERPRISE_URL }}
 
      - name: Login to Nexus Registry
        uses: docker/login-action@v3
        with:
          registry: vmclxnexusp01.corp.equinix.com:9052
          username: ${{ env.DOCKER_NEXUS_USERNAME }}
          password: ${{ env.DOCKER_NEXUS_PASSWORD }}
 
      - name: Docker Build
        run: |
          DOCKER_TAG=$(echo $GITHUB_SHA | cut -c 1-7)_$GITHUB_RUN_NUMBER
          echo "DOCKER_IMAGE_TAG=$DOCKER_TAG" >> $GITHUB_OUTPUT
          echo "DOCKER_IMAGE_TAG=$DOCKER_TAG" >> $GITHUB_ENV
 
          docker image build --pull -t vmclxnexusp01.corp.equinix.com:9052/amp-dev/amp-clm-ms:$DOCKER_TAG . -f Dockerfile.dev
          docker image push vmclxnexusp01.corp.equinix.com:9052/amp-dev/amp-clm-ms:$DOCKER_TAG
 
      - name: Twistlock Container Scan
        uses: equinix-enterpriseapps/devsecops-container-scanner@main
        with:
          image-details: vmclxnexusp01.corp.equinix.com:9052/amp-dev/amp-clm-ms:$DOCKER_IMAGE_TAG
          prismacloud_username: ${{ env.PRISMACLOUD_USER }}
          prismacloud_password: ${{ env.PRISMACLOUD_PASSWORD }}
 
      - name: Fetch GitHub Token
        id: github-app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ env.GITHUB_APP_ID }}
          private-key: ${{ env.GITHUB_PRIVATE_KEY }}
          repositories: amp-gitops
 
      - name: Code Checkout
        uses: actions/checkout@v4
        with: 
          repository: 'equinix-private/amp-gitops'
          path: 'gitops'
          ref: 'main'
          token: ${{ steps.github-app.outputs.token }}
          fetch-depth: 1

      # ============================================================
      # ✅ NEW SECTION: Update kustomization.yml with new Docker image tag
      # ============================================================
      - name: Install yq for YAML editing
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update image tag in amp-clm-ms/dev/kustomization.yml
        working-directory: ./gitops
        env:
          IMAGE_NAME: "sv2lxnxaappr001.corp.equinix.com:8001/clmrepo/amp-clm-ms-dev"
          NEW_TAG: ${{ env.DOCKER_IMAGE_TAG }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          set -euo pipefail
          FILE_PATH="amp-clm-ms/${ENVIRONMENT}/kustomization.yml"

          echo "Updating image tag in: ${FILE_PATH}"
          echo "Using Docker tag: ${NEW_TAG}"

          if [ ! -f "$FILE_PATH" ]; then
            echo "ERROR: File not found: $FILE_PATH"
            exit 1
          fi

          # Update newTag value for the specific image
          yq e -i ".images[] |= (select(.name == \"${IMAGE_NAME}\") .newTag = \"${NEW_TAG}\")" "$FILE_PATH"

          echo "Updated content:"
          cat "$FILE_PATH"

          git add "$FILE_PATH"

      - name: Commit and push updated tag to amp-gitops
        working-directory: ./gitops
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          NEW_TAG: ${{ env.DOCKER_IMAGE_TAG }}
        run: |
          set -euo pipefail
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git pull origin main

          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi

          git commit -m "ci: update amp-clm-ms image tag to ${NEW_TAG} for ${ENVIRONMENT}"
          git push origin main
          echo "Successfully pushed updated tag ${NEW_TAG} to GitOps repo."
      # ============================================================

      - name: update image tag
        run: |
          cd gitops
          echo ${{ inputs.environment }}
          echo $DOCKER_IMAGE_TAG
 
      - name: commit image tag to repository
        run: |
          cd gitops
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git pull origin
          git commit -a -m "GHA Commit for amp-clm-ms in ${{ inputs.environment }} for ${{ inputs.image_tag }}"
          git push
 
      - name: Send Failure Email Notification
        if: failure()
        timeout-minutes: 1
        uses: dawidd6/action-send-mail@v3
        with:
           server_address: sv2maillb.corp.equinix.com
           server_port: 25
           subject: AMP CI - Failure Notification
           to: sbashashaik@equinix.com
           cc: sbashashaik@equinix.com
           from: no-reply <devsecops-no-reply@equinix.com>
           body: |
                Hi Team,
                AMP CI execution failed. Please check the logs and apply the fix.
 
                Service Name:- ${{ inputs.module}}
                Environment Name:- ${{ inputs.environment }}
                Branch:- ${{ inputs.branch}}
                Requestor:- ${{ github.actor }}
                URL:- ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
           priority: normal
